# 데이터 증강 라벨링 이미지 처리 데이터셋 구현 
## 텐서 기본실습
    94p~

텐서(tensor)는 배열(array)이나 행렬(matrix)과 매우 유사한 특수한 자료구조입니다.

PyTorch에서는 텐서를 사용하여 모델의 입력과 출력뿐만 아니라 모델의 매개변수를 부호화(encode)합니다.

GPU나 다른 연산 가속을 위한 특수한 하드웨어에서 실행할 수 있다는 점을 제외하면, 텐서는 NumPy의 ndarra와 매우 유사합니다. 만약 ndarray에 익숙하다면 Tensor API를 바로 사용할 수 있습니다.

In [4]:
import torch
import numpy as np

### 1. 텐서 초기화하기

In [13]:
data = [[1, 2], [3, 4]]

x_data = torch.tensor(data)
print(x_data)
print(x_data.shape)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])


### 2. numpy 배열로부터 생성
numpy 버전에 따라 달라서 확인해 봐야함

In [12]:
# np_array = np.array(data).reshape
# x_np = torch.from_numpy(np_array)
# print(x_np)

### 3. 다른 텐서로부터 생성하기

In [8]:
data = [[1, 2], [3, 4]]

x_data = torch.tensor(data)

x_ones = torch.ones_like(x_data)
print(f"Ones Tensor >> \n", x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"random Tensor >> \n", x_rand)

Ones Tensor >> 
 tensor([[1, 1],
        [1, 1]])
random Tensor >> 
 tensor([[0.9614, 0.7822],
        [0.4922, 0.0947]])


명시적으로 재정의(override)하지 않는다면, 인자로 주어진 텐서의 속성(모양(shape), 자료형(datatype))을 유지합니다.

### 4. 무작위(random) 또는 상수(constant) 값을 사용하기

In [9]:
shape = (3, 3) 
randn_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor >> \n {randn_tensor} \n")
print(f"Ones Tensor >> \n {ones_tensor} \n")
print(f"Zeros Tensor >> \n {zeros_tensor} \n")

Random Tensor >> 
 tensor([[0.1742, 0.7725, 0.9774],
        [0.7772, 0.8043, 0.5651],
        [0.4203, 0.2756, 0.7703]]) 

Ones Tensor >> 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor >> 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 



### 5. 텐서의 속성(Attribute)
텐서의 속성은 텐서의 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지를 나타냅니다.

In [11]:
tensor = torch.rand(3, 4)
print(f"shape of tensor: {tensor.shape}")
print(f"data type of tensor: {tensor.dtype}")
print(f"device tensor is stored on: {tensor.device}")

shape of tensor: torch.Size([3, 4])
data type of tensor: torch.float32
device tensor is stored on: cpu


### 6. 텐서 연산(Operation)
전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 임의 샘플링(random sampling)등, 100가지 이상의 텐서 연산들을 여기에서 확인할 수 있습니다. 

각 연산들은 (일반적으로 CPU보다 빠른) GPU에서 실행할 수 있습니다. 

Colab을 사용한다면, Edit> Notebook Settings 에서 GPU로 할당할 수 있습니다.

<!-- # # 2 numpy 배열로부터 생성 => numpy 버전에 따라 달라서 확인해 봐야함

# np_array = np.array(data).reshape
# x_np = torch.from_numpy(np_array)
# print(x_np) -->

In [14]:
tensor = torch.rand(3, 4)
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
else:
    tensor = tensor.to("cpu")
    
print(f"Device tensor is stored on: {tensor.device}")


Device tensor is stored on: cuda:0


### 7. Numpy식의 표준 인덱싱과 슬라이싱

In [15]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 3    
print(tensor)

tensor([[1., 3., 1., 1.],
        [1., 3., 1., 1.],
        [1., 3., 1., 1.],
        [1., 3., 1., 1.]])


### 8. 텐서 합치기 & 텐서 곱하기

In [16]:
tensor = torch.ones(4, 4)
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

print(tensor * tensor)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


### 9. 두 텐서 간의 행렬 곱(matrix multiplication)

In [20]:
tensor = torch.ones(4, 4)
print(tensor)
print(tensor.matmul(tensor.T))
print(tensor @ tensor.T)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])
tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])


### 10. 바꿔치기(in-place)

바꿔치기 연산은 메모리를 일부 절약하지만, 기록(history)이 즉시 삭제되어 도함수(derivative) 계산에 문제가 발생할 수 있습니다. 따라서 사용을 권장하지 않습니다.

In [21]:
tensor.add_(5)
print(tensor)

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])


### 12. NumPy 변환(Bridge)

In [22]:
t =  torch.ones(5)
print("tensor -> ", t)

n = t.numpy()
print("numpy -> ", n)


tensor ->  tensor([1., 1., 1., 1., 1.])
numpy ->  [1. 1. 1. 1. 1.]


CPU상의 텐서와 NumPy배열은 메모리 공간을 공유하기 떄문에, 하나를 변경하면 다른 하나도 변경됩니다.

In [23]:
t.add_(1)
n = t.numpy()
print(t)
print(n)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 13.Numpy 배열을 텐서로 변환하기

In [25]:
n = np.ones(5)
t = torch.from_numpy(n)

print(n)
print(t)

np.add(n, 1, out=n)
print(n)
print(t)


[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### 14. 뷰(view) - 원소의 수를 유지하면서 텐서의 크기 변경. 매우 중요함!!

파이토치 텐서의 뷰(view)는 넘파이에서의 리쉐이프(Reshape)와 같은 역할을 합니다.   
Reshape라는 이름에서 알 수 있듯이, 텐서의 크기(Shape)를 변경해주는 역할을 합니다.   
실습을 위해 우선 임의로 다음과 같이 3차원 텐서를 만듭니다.


In [35]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)
print(t)

torch.Size([2, 2, 3])
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


- 3차원 텐서에서 2차원 텐서로 변경

In [34]:
print(ft.view([-1, 3]))     # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


view([-1, 3])이 가지는 의미는 이와 같습니다.   

 -1은 첫번째 차원은 사용자가 잘 모르겠으니 파이토치에 맡기겠다는 의미이고, 3은 두번째 차원의 길이는 3을 가지도록 하라는 의미입니다. 
 
다시 말해 현재 3차원 텐서를 2차원 텐서로 변경하되 (?, 3)의 크기로 변경하라는 의미입니다. 결과적으로 (4, 3)의 크기를 가지는 텐서를 얻었습니다.

내부적으로 크기 변환은 다음과 같이 이루어졌습니다. (2, 2, 3) -> (2 × 2, 3) -> (4, 3)


### view 규칙

• view는 기본적으로 변경 전과 변경 후의 텐서 안의 원소의 개수가 유지되어야 합니다.   
• 파이토치의 view는 사이즈가 -1로 설정되면 다른 차원으로부터 해당 값을 유추합니다.

변경 전 텐서의 원소의 수는 (2 × 2 × 3) = 12개였습니다. 그리고 변경 후 텐서의 원소의 개수 또한 (4 × 3) = 12개였
습니다.   
   


- 3차원 텐서의 크기 변경

이번에는 3차원 텐서에서 3차원 텐서로 차원은 유지하되, 크기(shape)를 바꾸는 작업을 해보겠습니다.   
view로 텐서의 크기를 변경하더라도 원소의 수는 유지되어야 한다고 언급한 바 있습니다.   
 
그렇다면 (2 × 2 × 3) 텐서를 (? × 1 × 3) 텐서로 변경하라고 하면 ?는 몇 차원인가요?
(2 × 2 × 3) = (? × 1 × 3) = 12를 만족해야 하므로 ?는 4가 됩니다. 


In [37]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### 15. 스퀴즈(Squeeze) - 1인 차원을 제거한다.

In [38]:
# 3X1
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


해당 텐서는 (3 × 1)의 크기를 가집니다. 두번째 차원이 1이므로 squeeze를 사용하면 (3,)의 크기를 가지는
텐서로 변경됩니다.

In [39]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


위의 결과는 1이었던 두번째 차원이 제거되면서 (3,)의 크기를 가지는 텐서로 변경되어 1차원 벡터가 된 것을
보여줍니다.


### 16. 언스쿼즈(Unsqueeze) - 특정 위치에 1인 차원을 추가한다.
언스퀴즈는 스퀴즈와 정반대입니다. 특정 위치에 1인 차원을 추가할 수 있습니다.   
실습을 위해 임의로 (3,)의 크기를 가지는 1인 차원 텐서를 만들겠습니다.

In [45]:
ft = torch.Tensor([0, 1, 2])
print(ft)
print(ft.shape)

tensor([0., 1., 2.])
torch.Size([3])


현재는 차원이 1개인 1차원 벡터입니다. 여기에 첫번째 차원에 1인 차원을 추가해보겠습니다. 첫번째 차원의 인
덱스를 의미하는 숫자 0을 인자로 넣으면 첫번째 차원에 1인 차원이 추가됩니다.

In [41]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


위 결과는 (3,)의 크기를 가졌던 1차원 벡터가 (1, 3)의 2차원 텐서로 변경된 것을 보여줍니다. 방금 한 연산을 앞서
배운 view로도 구현 가능합니다. 2차원으로 바꾸고 싶으면서 첫번째 차원은 1이기를 원한다면 view에서 (1, -1)을
인자로 사용하면됩니다.

In [42]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


위의 결과는 unsqueeze와 view가 동일한 결과를 만든 것을 보여줍니다.

밑에 내용은 참고만하기 (위의 실습과 거의 동일함)   

이번에는 unsqueeze의 인자로 1을 넣어보겠습니다. 인덱스는 0부터 시작하므로 이는 두번째 차원에 1을 추가하겠
다는 것을 의미합니다. 현재 크기는 (3,)이었으므로 두번째 차원에 1인 차원을 추가하면 (3, 1)의 크기를 가지게 됩
니다. 

In [43]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


이번에는 unsqueeze의 인자로 -1을 넣어보겠습니다. -1은 인덱스 상으로 마지막 차원을 의미합니다. 현재 크기는
(3,)이었으므로 마지막 차원에 1인 차원을 추가하면 (3, 1)의 크기를 가지게 됩니다. 다시 말해 현재 텐서의 경우에
는 1을 넣은 경우와 -1을 넣은 경우가 결과가 동일합니다. 


In [44]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


맨 뒤에 1인 차원이 추가되면서 1차원 벡터가 (3, 1)의 크기를 가지는 2차원 텐서로 변경되었습니다.
