https://github.com/chandrikadeb7/Face-Mask-Detection

참고자료

In [3]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
# 0으로 초기화된 배열
arr = np.zeros ((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# 빈 값으로 만들어진 배열
arr = np.empty((4,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
# 1로 가득찬 배열을 만든다
arr = np.ones((3,3))

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
# 배열의 생성
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
# ndarray 배열의 모양, 차수, 데이터 타입 확인
# 차원 확인하는 법 => [[ 수 = 차원
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [12]:
arr.shape

(2, 3)

In [13]:
arr.ndim

2

In [14]:
arr.dtype

dtype('int64')

In [15]:
arr_float = arr.astype(np.float64)
arr_float.dtype

dtype('float64')

In [16]:
arr_str = np.array(['1','2','3'])
arr_str.dtype

dtype('<U1')

In [17]:
arr_int = arr_str.astype(np.int64)
arr_int.dtype

dtype('int64')

In [20]:
# ndarry 배열의 연산

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

In [21]:
arr1 + arr2

array([[ 6,  8],
       [10, 12]])

In [22]:
np.add(arr1, arr2)

array([[ 6,  8],
       [10, 12]])

In [23]:
arr1 * arr2

array([[ 5, 12],
       [21, 32]])

In [24]:
np.multiply(arr1, arr2)

array([[ 5, 12],
       [21, 32]])

In [25]:
#ndarray 배열 슬라이싱 하기
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [26]:
arr.ndim

2

In [27]:
arr_1 = arr[:2,1:3]
print(arr_1)
# 123    [:2]  -> 123/ 456
# 456    [1:3] -> 23/ 56/ 89
# 789

[[2 3]
 [5 6]]


In [28]:
arr[0,2]

3

In [30]:
arr[[0,1,2],[2,0,1]]

# 123    [0,1,2]  -> 모두 선택(큰배열 선택)
# 456    [2,0,1] -> 첫번째 배열의 2번째요소/ 두번째 배열의 0번째 요소... (배열안의 요소 선택)
# 789

array([3, 4, 8])

In [31]:
idx = arr > 3
print(idx)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [32]:
print(arr[idx])

[4 5 6 7 8 9]


In [36]:
redwine = np.loadtxt(fname = 'winequality-red.csv', delimiter=';', skiprows=1)
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [38]:
print(redwine.sum())  #합계

7.926036165311652


In [39]:
print(redwine.mean()) #평균

7.926036165311652


In [41]:
# 축(axis)
print(redwine.sum(axis=0))

[13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]


In [42]:
print(redwine.mean(axis=0))

[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]


In [43]:
redwine[:,0] #=>[전체데이터:0번째 컬럼(세로줄)]

array([7.4, 7.8, 7.8, ..., 6.3, 5.9, 6. ])

In [45]:
redwine.max(axis=0) # 각 컬럼별 최대값

array([ 15.9    ,   1.58   ,   1.     ,  15.5    ,   0.611  ,  72.     ,
       289.     ,   1.00369,   4.01   ,   2.     ,  14.9    ,   8.     ])

In [46]:
redwine.min(axis=0) # 각 컬럼별 최소값

array([4.6    , 0.12   , 0.     , 0.9    , 0.012  , 1.     , 6.     ,
       0.99007, 2.74   , 0.33   , 8.4    , 3.     ])